
# "service" is the name of this project. This will also be added to your AWS resource names.
service: product-service


provider:
  name: aws
  runtime: nodejs18.x
  stage: "dev"
  region: us-east-1

functions:
  createProduct:
    handler: dist/index.CreateProductHandler
    timeout: 30  # Increase timeout to 30 seconds
    memorySize: 1024  # Allocate 1 GB of memory
    events:
      - httpApi:
          path: product
          method: post
  
  getProductbyid:
    handler: dist/index.GetProductByIdHandler
    timeout: 30  # Increase timeout to 30 seconds
    memorySize: 1024  # Allocate 1 GB of memory
    events:
      - httpApi:
          path: product/{id}
          method: get   
                    
  getAllProduct:
    handler: dist/index.GetAllProductHandler
    timeout: 30  # Increase timeout to 30 seconds
    memorySize: 1024  # Allocate 1 GB of memory
    events:
      - httpApi:
          path: product
          method: get     

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0  # Listen on all network interfaces
    httpPort: 3000      # Expose the service on port 3000
